name: CI Pipeline

on:
  pull_request:
    branches:
      - "main"
permissions:
  contents: read

jobs:
  build-env:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          python-version: "3.12"
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: lenapy_env
          environment-file: environment.yml
          auto-activate-base: false

      - name: Install dependencies
        shell: bash -l {0}
        run: |
          pip install -e .[test]
